import type { SearchQueryRow } from "@/lib/searches/queries";
import type { Database } from "@/types/supabase";

type CompanyInsert = Database["public"]["Tables"]["companies"]["Insert"];

const SUFFIXES = [
  "Group",
  "BV",
  "Ltd",
  "GmbH",
  "SAS",
  "Inc",
  "Partners",
  "Studio",
  "Services",
  "Solutions",
];

function slugify(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

function pick<T>(items: T[], index: number, fallback: T): T {
  if (!items.length) return fallback;
  return items[index % items.length] ?? fallback;
}

export type MockCompanySeed = Omit<
  CompanyInsert,
  "id" | "created_at" | "updated_at" | "first_found_at"
> & {
  sourceUrl: string;
};

/**
 * Deterministic mock companies from a search query — no network.
 */
export function buildMockCompaniesForPage(input: {
  organizationId: string;
  searchQuery: SearchQueryRow;
  jobId: string;
  pageIndex: number;
  count: number;
}): MockCompanySeed[] {
  const keyword =
    input.searchQuery.keywords[0] ??
    input.searchQuery.keyword ??
    "Business";
  const industry =
    input.searchQuery.industries[0] ??
    input.searchQuery.industry ??
    "professional_services";
  const country =
    input.searchQuery.countries[0] ?? input.searchQuery.country ?? "NL";
  const city = pick(
    input.searchQuery.cities,
    input.pageIndex,
    input.searchQuery.city ?? "Amsterdam",
  );
  const region = pick(
    input.searchQuery.regions,
    input.pageIndex,
    input.searchQuery.region ?? "",
  );

  const results: MockCompanySeed[] = [];

  for (let i = 0; i < input.count; i += 1) {
    const n = input.pageIndex * input.count + i + 1;
    const suffix = pick(SUFFIXES, n, "Group");
    const companyName = `${keyword} ${suffix} ${n}`;
    const domain = `${slugify(companyName) || "mock-co"}.example`;
    const websiteUrl = `https://${domain}`;
    const sourceUrl = `https://mock.lead-engine.local/jobs/${input.jobId}/page/${input.pageIndex + 1}/item/${i + 1}`;

    results.push({
      organization_id: input.organizationId,
      company_name: companyName,
      normalized_company_name: companyName.toLowerCase().trim(),
      website_url: websiteUrl,
      normalized_domain: domain,
      description: `Mock discovery result for “${input.searchQuery.name}” (page ${input.pageIndex + 1}).`,
      industry,
      city,
      region: region || null,
      country,
      postal_code: null,
      phone: null,
      linkedin_url: input.searchQuery.linkedin_required
        ? `https://www.linkedin.com/company/${slugify(companyName)}`
        : null,
      facebook_url: null,
      instagram_url: null,
      source_url: sourceUrl,
      source_type: "search_result",
      last_checked_at: new Date().toISOString(),
      status: "new",
      notes: "Generated by mock scrape engine (fase 4).",
      sourceUrl,
    });
  }

  return results;
}
