/**
 * System integration catalog — plugin manifests (no DB seed required).
 */

import type { IntegrationManifest } from "@/lib/integrations/types";

function m(
  partial: Omit<IntegrationManifest, "supportsManualSync" | "supportsScheduledSync" | "supportsIncrementalSync" | "supportsWebhooks"> &
    Partial<
      Pick<
        IntegrationManifest,
        | "supportsManualSync"
        | "supportsScheduledSync"
        | "supportsIncrementalSync"
        | "supportsWebhooks"
      >
    >,
): IntegrationManifest {
  return {
    supportsManualSync: true,
    supportsScheduledSync: true,
    supportsIncrementalSync: true,
    supportsWebhooks: false,
    ...partial,
  };
}

export const INTEGRATION_CATALOG: IntegrationManifest[] = [
  m({
    code: "google_workspace",
    name: "Google Workspace",
    description: "Connect Gmail, Drive, and Calendar for sales collaboration.",
    category: "productivity",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["email_send", "calendar", "file_storage"],
    permissions: ["email.read", "drive.file", "calendar.events"],
    documentationUrl: "/integrations/google_workspace",
    status: "available",
    featured: true,
    popularRank: 1,
    releasedAt: "2026-07-01",
    oauth: {
      authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: [
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/calendar.events",
      ],
      pkce: true,
      clientIdEnv: "INTEGRATION_GOOGLE_CLIENT_ID",
      clientSecretEnv: "INTEGRATION_GOOGLE_CLIENT_SECRET",
    },
    supportsWebhooks: true,
  }),
  m({
    code: "microsoft_365",
    name: "Microsoft 365",
    description: "Outlook, OneDrive, and Teams calendar for CRM workflows.",
    category: "productivity",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["email_send", "calendar", "file_storage", "messaging"],
    permissions: ["Mail.Read", "Files.ReadWrite", "Calendars.ReadWrite"],
    documentationUrl: "/integrations/microsoft_365",
    status: "available",
    featured: true,
    popularRank: 2,
    releasedAt: "2026-07-01",
    oauth: {
      authorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
      tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
      scopes: ["offline_access", "Files.ReadWrite", "Calendars.ReadWrite"],
      pkce: true,
      clientIdEnv: "INTEGRATION_MS365_CLIENT_ID",
      clientSecretEnv: "INTEGRATION_MS365_CLIENT_SECRET",
    },
  }),
  m({
    code: "slack",
    name: "Slack",
    description: "Notify channels about deals, tasks, and automation events.",
    category: "communication",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["messaging", "webhooks"],
    permissions: ["chat:write", "channels:read"],
    documentationUrl: "/integrations/slack",
    status: "available",
    featured: true,
    popularRank: 3,
    releasedAt: "2026-07-01",
    oauth: {
      authorizeUrl: "https://slack.com/oauth/v2/authorize",
      tokenUrl: "https://slack.com/api/oauth.v2.access",
      scopes: ["chat:write", "channels:read"],
      pkce: false,
      clientIdEnv: "INTEGRATION_SLACK_CLIENT_ID",
      clientSecretEnv: "INTEGRATION_SLACK_CLIENT_SECRET",
    },
    supportsWebhooks: true,
  }),
  m({
    code: "microsoft_teams",
    name: "Microsoft Teams",
    description: "Post sales alerts and meeting summaries to Teams channels.",
    category: "communication",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["messaging"],
    permissions: ["ChannelMessage.Send"],
    documentationUrl: "/integrations/microsoft_teams",
    status: "available",
    featured: true,
    popularRank: 4,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "hubspot",
    name: "HubSpot",
    description: "Two-way sync of companies, contacts, and deals with HubSpot CRM.",
    category: "crm",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["contacts_sync", "companies_sync", "deals_sync"],
    permissions: ["crm.objects.contacts.read", "crm.objects.companies.write"],
    documentationUrl: "/integrations/hubspot",
    status: "available",
    featured: true,
    popularRank: 5,
    releasedAt: "2026-07-01",
    oauth: {
      authorizeUrl: "https://app.hubspot.com/oauth/authorize",
      tokenUrl: "https://api.hubapi.com/oauth/v1/token",
      scopes: ["crm.objects.contacts.read", "crm.objects.companies.write"],
      pkce: false,
      clientIdEnv: "INTEGRATION_HUBSPOT_CLIENT_ID",
      clientSecretEnv: "INTEGRATION_HUBSPOT_CLIENT_SECRET",
    },
  }),
  m({
    code: "salesforce",
    name: "Salesforce",
    description: "Enterprise CRM sync for accounts, contacts, and opportunities.",
    category: "crm",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["contacts_sync", "companies_sync", "deals_sync"],
    permissions: ["api", "refresh_token"],
    documentationUrl: "/integrations/salesforce",
    status: "available",
    featured: true,
    popularRank: 6,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "pipedrive",
    name: "Pipedrive",
    description: "Pipeline-focused CRM sync for deals and activities.",
    category: "crm",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["deals_sync", "contacts_sync"],
    permissions: ["deals:full", "persons:full"],
    documentationUrl: "/integrations/pipedrive",
    status: "available",
    featured: true,
    popularRank: 10,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "zoho_crm",
    name: "Zoho CRM",
    description: "Sync leads and deals with Zoho CRM modules.",
    category: "crm",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["contacts_sync", "deals_sync"],
    permissions: ["ZohoCRM.modules.ALL"],
    documentationUrl: "/integrations/zoho_crm",
    status: "beta",
    featured: true,
    popularRank: 18,
    releasedAt: "2026-07-15",
  }),
  m({
    code: "notion",
    name: "Notion",
    description: "Export company briefs and playbooks to Notion databases.",
    category: "productivity",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["file_storage"],
    permissions: ["read", "write"],
    documentationUrl: "/integrations/notion",
    status: "available",
    featured: true,
    popularRank: 12,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "airtable",
    name: "Airtable",
    description: "Push lead lists and campaign results into Airtable bases.",
    category: "productivity",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["companies_sync", "contacts_sync"],
    permissions: ["data.records:read", "data.records:write"],
    documentationUrl: "/integrations/airtable",
    status: "available",
    featured: true,
    popularRank: 14,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "zapier",
    name: "Zapier",
    description: "Trigger Zaps from Storaflow events without custom code.",
    category: "automation",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "api_key",
    features: ["automation_bridge", "webhooks"],
    permissions: ["webhooks.manage"],
    documentationUrl: "/integrations/zapier",
    status: "available",
    featured: true,
    popularRank: 7,
    releasedAt: "2026-07-01",
    supportsWebhooks: true,
  }),
  m({
    code: "make",
    name: "Make",
    description: "Connect Storaflow scenarios to Make.com automation.",
    category: "automation",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "api_key",
    features: ["automation_bridge", "webhooks"],
    permissions: ["webhooks.manage"],
    documentationUrl: "/integrations/make",
    status: "available",
    featured: true,
    popularRank: 11,
    releasedAt: "2026-07-01",
    supportsWebhooks: true,
  }),
  m({
    code: "shopify",
    name: "Shopify",
    description: "Import customers and orders from Shopify stores.",
    category: "ecommerce",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["contacts_sync", "companies_sync"],
    permissions: ["read_customers", "read_orders"],
    documentationUrl: "/integrations/shopify",
    status: "available",
    featured: true,
    popularRank: 9,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "woocommerce",
    name: "WooCommerce",
    description: "Sync WooCommerce customers into Storaflow companies.",
    category: "ecommerce",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "api_key",
    features: ["contacts_sync"],
    permissions: ["read", "write"],
    documentationUrl: "/integrations/woocommerce",
    status: "available",
    featured: true,
    popularRank: 16,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "stripe",
    name: "Stripe",
    description: "Import customer and payment signals for revenue context.",
    category: "finance",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["payments"],
    permissions: ["read_customers", "read_charges"],
    documentationUrl: "/integrations/stripe",
    status: "available",
    featured: true,
    popularRank: 8,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "quickbooks",
    name: "QuickBooks",
    description: "Accounting sync for invoices and customers.",
    category: "accounting",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["accounting"],
    permissions: ["com.intuit.quickbooks.accounting"],
    documentationUrl: "/integrations/quickbooks",
    status: "beta",
    featured: true,
    popularRank: 17,
    releasedAt: "2026-07-10",
  }),
  m({
    code: "xero",
    name: "Xero",
    description: "Connect Xero contacts and invoices to CRM accounts.",
    category: "accounting",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["accounting"],
    permissions: ["accounting.contacts", "accounting.transactions"],
    documentationUrl: "/integrations/xero",
    status: "coming_soon",
    featured: true,
    popularRank: 20,
    releasedAt: "2026-08-01",
  }),
  m({
    code: "dropbox",
    name: "Dropbox",
    description: "Store proposals and exports in Dropbox folders.",
    category: "storage",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["file_storage"],
    permissions: ["files.content.write"],
    documentationUrl: "/integrations/dropbox",
    status: "available",
    featured: true,
    popularRank: 15,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "google_drive",
    name: "Google Drive",
    description: "Upload proposals and campaign assets to Google Drive.",
    category: "storage",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["file_storage"],
    permissions: ["drive.file"],
    documentationUrl: "/integrations/google_drive",
    status: "available",
    featured: true,
    popularRank: 13,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "onedrive",
    name: "OneDrive",
    description: "Microsoft OneDrive file storage for sales documents.",
    category: "storage",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "oauth2",
    features: ["file_storage"],
    permissions: ["Files.ReadWrite"],
    documentationUrl: "/integrations/onedrive",
    status: "available",
    featured: true,
    popularRank: 19,
    releasedAt: "2026-07-01",
  }),
  m({
    code: "openai",
    name: "OpenAI",
    description: "Bring your own OpenAI key for Copilot and email AI.",
    category: "ai_providers",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "api_key",
    features: ["ai_provider"],
    permissions: ["api.completions"],
    documentationUrl: "/integrations/openai",
    status: "available",
    featured: true,
    popularRank: 1,
    releasedAt: "2026-06-01",
    supportsScheduledSync: false,
    supportsIncrementalSync: false,
  }),
  m({
    code: "anthropic",
    name: "Anthropic",
    description: "Connect Claude models as an alternate AI provider.",
    category: "ai_providers",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "api_key",
    features: ["ai_provider"],
    permissions: ["api.messages"],
    documentationUrl: "/integrations/anthropic",
    status: "available",
    featured: true,
    popularRank: 2,
    releasedAt: "2026-07-01",
    supportsScheduledSync: false,
    supportsIncrementalSync: false,
  }),
  m({
    code: "google_gemini",
    name: "Google Gemini",
    description: "Use Gemini models for summarization and drafting.",
    category: "ai_providers",
    developer: "Storaflow",
    version: "1.0.0",
    authType: "api_key",
    features: ["ai_provider"],
    permissions: ["generativelanguage"],
    documentationUrl: "/integrations/google_gemini",
    status: "beta",
    featured: true,
    popularRank: 3,
    releasedAt: "2026-07-20",
    supportsScheduledSync: false,
    supportsIncrementalSync: false,
  }),
];

export function getIntegrationManifest(
  code: string,
): IntegrationManifest | null {
  return INTEGRATION_CATALOG.find((i) => i.code === code) ?? null;
}

export function listIntegrationCatalog(filters?: {
  query?: string;
  category?: string;
  status?: string;
  installedOnly?: boolean;
  installedCodes?: string[];
  sort?: "popular" | "newest" | "alphabetical";
}): IntegrationManifest[] {
  let rows = [...INTEGRATION_CATALOG];
  if (filters?.category && filters.category !== "all") {
    rows = rows.filter((r) => r.category === filters.category);
  }
  if (filters?.status && filters.status !== "all") {
    rows = rows.filter((r) => r.status === filters.status);
  }
  if (filters?.installedOnly && filters.installedCodes) {
    const set = new Set(filters.installedCodes);
    rows = rows.filter((r) => set.has(r.code));
  }
  if (filters?.query?.trim()) {
    const needle = filters.query.trim().toLowerCase();
    rows = rows.filter(
      (r) =>
        r.name.toLowerCase().includes(needle) ||
        r.code.toLowerCase().includes(needle) ||
        r.description.toLowerCase().includes(needle) ||
        r.developer.toLowerCase().includes(needle),
    );
  }
  const sort = filters?.sort ?? "popular";
  if (sort === "alphabetical") {
    rows.sort((a, b) => a.name.localeCompare(b.name));
  } else if (sort === "newest") {
    rows.sort((a, b) => b.releasedAt.localeCompare(a.releasedAt));
  } else {
    rows.sort((a, b) => a.popularRank - b.popularRank);
  }
  return rows;
}
